### ISSUE TITLE
[Question]: Missing AL2 images on Dockerhub

### ISSUE THREAD

**Issue by arredond** [amazonlinux/container-images#100]
### Product

Amazon Linux 2

### What is your question?

Similar to #96 and #97, the [October version of AL2 ](https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20231016.html) came out over a week ago. I've seen in the docs and other issues that "The DockerHub updates can be delayed by upto 1 week from the date of an official AMI release version.", which makes perfect sense.

This is just a little ping since we crossed that 1 week barrier. I'm particularly interested in this upgrade because it provides updated packages that fix a number of CVEs that arose recently (most around `curl` and `libcurl`).

Also, a more general question: is there a specific day of the week that these updates to Docker Hub are made? What's the best way to monitor these updates without bothering the team? In this case, I've checked for existing PRs in both this repo and the Docker oficial images one, without finding anything relevant.

**Comment by sktomer** [comment]
We had a quick follow update to the AMIs that got delayed. But we should be doing a better job at keeping dockerhub up to date. Let me first push out the latest update and then update this thread.

**Comment by sktomer** [comment]
Awaiting merge: https://github.com/docker-library/official-images/pull/15613

**Comment by dadetayo** [comment]
Merge is complete!
