### ISSUE TITLE
[Question]: amazonlinux2 container images showing vulnerability

### ISSUE THREAD

**Issue by sawanverma** [amazonlinux/container-images#105]
### Product

Amazon Linux 2

### What is your question?

The containter image of amazonlinux 2 is showing medium vulnerability for nss-softokn:3.90.0-6.amzn2 package. When can we expect the fixed updated latest tag for amazonlinux 2?

**Comment by sktomer** [comment]
Hello, 

Could you please provide the CVE information or link so we can look into this ?

**Comment by sktomer** [comment]
Closing due to no customer response. Please reopen if you're still affected and provide the requested details.
