### ISSUE TITLE
Upgrade rpm package to >= 4.16.0

### ISSUE THREAD

**Issue by benipeled** [amazonlinux/container-images#107]
### Product

Amazon Linux 2

### Package

rpm-4.16.0 or higher

### Why do you need this package?

To import an EDDSA rpm-key - the EDDSA support was added in 4.16.0 - https://rpm.org/wiki/Releases/4.16.0

**Comment by sktomer** [comment]
`rpm` is one of the core components that define an OS distro. Bumping the version can have large scale implications and compatibility issues. We are not likely to support this for Amazon Linux 2.

Have you considered using Amazon Linux 2023 ?

```
$ sudo dnf list rpm system-release
Last metadata expiration check: 0:00:53 ago on Thu Mar  7 18:58:54 2024.
Installed Packages
rpm.x86_64                                                      4.16.1.3-12.amzn2023.0.6                                             @System
system-release.noarch                                           2023.3.20240304-0.amzn2023                                           @System
```

**Comment by benipeled** [comment]
> `rpm` is one of the core components that define an OS distro. Bumping the version can have large scale implications and compatibility issues. We are not likely to support this for Amazon Linux 2.
> 
> Have you considered using Amazon Linux 2023 ?

I tried to avoid it since Amazon Linux 2 EOL is mid.2025 but if it's not going to be updated, I probably have no other option,
Thanks,

**Comment by sktomer** [comment]
Closing as won't fix. Please reopen if you have issues getting this working on AL2023.
