### ISSUE TITLE
[Security]: Latest amazonlinux images showing vulnerabilities

### ISSUE THREAD

**Issue by dmattia** [amazonlinux/container-images#109]
### Product

Amazon Linux 2023

### What is your question?

On https://hub.docker.com/_/amazonlinux/tags, it shows some high and medium vulnerabilities on the latest images, which at this time appears to be [2023.4.20240416.0](https://hub.docker.com/layers/library/amazonlinux/2023.4.20240416.0/images/sha256-6966527bf9107ed0fdf2cb8f943613ad9ce02b41f2a28797eae6e5bdbbe844f0?context=explore).

<img width="1184" alt="Screenshot 2024-06-04 at 12 42 13 PM" src="https://github.com/amazonlinux/container-images/assets/8922077/1fa79469-98af-45c5-afa6-cc7ad2d1c292">

Likewise, I see similar CVEs listed when I scan my image based on this latest version in AWS Inspector Enhanced:

<img width="1092" alt="Screenshot 2024-06-04 at 12 43 16 PM" src="https://github.com/amazonlinux/container-images/assets/8922077/f187031c-6750-439c-8e08-06865dfaa054">

Is there an estimated release date for the next version, and have these vulnerabilities been worked around?

**Comment by sktomer** [comment]
Images have been updated. Apologies for the delay. 
We are improving our processes to avoid delays going forward.
Please re-open this issue if you still have concerns.
Thank you for reaching out to us.

**Comment by sktomer** [comment]
![Screenshot 2024-06-06 at 11 08 58 AM](https://github.com/amazonlinux/container-images/assets/11709967/09731a5e-7b17-4a4c-9eac-8a14699724ef)
