### ISSUE TITLE
[Package] 

### ISSUE THREAD

**Issue by SavvasHemanthDuvvuru** [amazonlinux/container-images#110]
### Product

Amazon Linux 2023

### Package

yum package and libnl package

### Why do you need this package?

Unable to install yum package and libnl package 

Step 4/23 : RUN dnf install -y yum
--
8468 | ---> Running in e05e66d5b0b6
8469 | error: Could not depsolve transaction; 1 problem detected:
8470 | Problem: problem with installed package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64
8471 | - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from @System conflicts with dnf provided by dnf-4.12.0-2.amzn2023.0.4.noarch from amazonlinux
8472 | - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from amazonlinux conflicts with dnf provided by dnf-4.12.0-2.amzn2023.0.4.noarch from amazonlinux
8473 | - package yum-4.12.0-2.amzn2023.0.4.noarch from amazonlinux requires dnf = 4.12.0-2.amzn2023.0.4, but none of the providers can be installed
8474 | - conflicting requests
8475 | - package yum-4.14.0-1.amzn2023.0.4.noarch from amazonlinux requires dnf = 4.14.0-1.amzn2023.0.4, but none of the providers can be installed
8476 | - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from @System conflicts with dnf provided by dnf-4.14.0-1.amzn2023.0.4.noarch from amazonlinux
8477 | - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from amazonlinux conflicts with dnf provided by dnf-4.14.0-1.amzn2023.0.4.noarch from amazonlinux
8478 | The command '/bin/sh -c dnf install -y yum' returned a non-zero code: 1

error: open of libnl3-devel failed: No such file or directory
 The command '/bin/sh -c rpm -ivh libnl3-devel' returned a non-zero code: 1

**Comment by sktomer** [comment]
Description is not clear about whether this is an AMI issue or a container issue.
On al2023 container:
```
$ docker run -it amazonlinux:2023
bash-5.2# dnf install -y yum
Amazon Linux 2023 repository                                                                                                                                82 MB/s |  25 MB     00:00
Last metadata expiration check: 0:00:04 ago on Wed Jun 19 18:45:46 2024.
Package yum-4.12.0-2.amzn2023.0.4.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
bash-5.2#
```
Please open general Amazon Linux 2023 related issues here: https://github.com/amazonlinux/amazon-linux-2023/issues

**Comment by SavvasHemanthDuvvuru** [comment]
in our scenario we are running docker  using  amazonlinux 2023 minimal.

**Comment by sktomer** [comment]
Thanks for the clarification. I should have noticed `microdnf` in the original tracelog.

On a `al2023-minimal` container:

```
bash-5.2# ls -al /usr/bin/dnf
lrwxrwxrwx 1 root root 8 Feb  1  2023 /usr/bin/dnf -> microdnf
bash-5.2# dnf install yum -y
Downloading metadata...
error: Could not depsolve transaction; 1 problem detected:
 Problem: problem with installed package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64
  - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from @System conflicts with dnf provided by dnf-4.12.0-2.amzn2023.0.4.noarch from amazonlinux
  - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from amazonlinux conflicts with dnf provided by dnf-4.12.0-2.amzn2023.0.4.noarch from amazonlinux
  - package yum-4.12.0-2.amzn2023.0.4.noarch from amazonlinux requires dnf = 4.12.0-2.amzn2023.0.4, but none of the providers can be installed
  - conflicting requests
  - package yum-4.14.0-1.amzn2023.0.4.noarch from amazonlinux requires dnf = 4.14.0-1.amzn2023.0.4, but none of the providers can be installed
  - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from @System conflicts with dnf provided by dnf-4.14.0-1.amzn2023.0.4.noarch from amazonlinux
  - package microdnf-dnf-3.8.1-1.amzn2023.0.1.x86_64 from amazonlinux conflicts with dnf provided by dnf-4.14.0-1.amzn2023.0.4.noarch from amazonlinux
```

Trying to install `yum` requires `dnf` which conflicts with `microdnf` (which symlinks to `dnf`).
This seems like expected behavior as we don't want to install `dnf` in parallel with `microdnf`.

**Comment by sktomer** [comment]
Could you please elaborate more on what you're trying to accomplish by installing `yum` ?

**Comment by sktomer** [comment]
We are not planning to change this behavior without a good usage justification and need.

**Comment by SavvasHemanthDuvvuru** [comment]
i am trying to install the falcon sensor which  worked using amazon-linux2, now i am trying to use 
FROM public.ecr.aws/amazonlinux/amazonlinux:2023-minimal
ADD devops/TCR7/falcon-sensor-6.33.0-13003.amzn2.x86_64.rpm  /opt/
RUN dnf install /opt/falcon-sensor-6.33.0-13003.amzn2.x86_64.rpm -y

and it is not working with the below error

Step 10/19 : RUN dnf install falcon-sensor-6.33.0-13003.amzn2.x86_64.rpm -y
---> Running in bbef456002f2
error: No package matches 'falcon-sensor-6.33.0-13003.amzn2.x86_64.rpm'
The command '/bin/sh -c dnf install falcon-sensor-6.33.0-13003.amzn2.x86_64.rpm -y' returned a non-zero code: 1
 
[Container] 2024/06/05 13:28:36.242238 Command did not exit successfully docker build -t $REPOSITORY_URI:latest . exit status 1
[Container] 2024/06/05 13:28:36.255228 Phase complete: BUILD State: FAILED
[Container] 2024/06/05 13:28:36.255247 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build -t $REPOSITORY_URI:latest .. Reason: exit status 1
