### ISSUE TITLE
[Security]: Latest amazonlinux images showing vulnerabilities

### ISSUE THREAD

**Issue by onikroo** [amazonlinux/container-images#116]
### Product

Amazon Linux 2023

### What is your question?

The latest amazonlinux 2023 Docker image (build `2023.6.20241010` ) contains 2 High Severity CVEs.
![image](https://github.com/user-attachments/assets/70b5c1a4-4312-478b-b24f-b984e5c507ca)
Is this the best place to report these as needing to be patched?

**Comment by Luis-3M** [comment]
We've noticed the same issue using `amazonlinux:2023.6.20241010.0-minimal` image.
Temporary solution for us was to fallback to `amazonlinux:2023` and install the proper package version following AWS's suggestion: https://alas.aws.amazon.com/AL2023/ALAS-2024-742.html

**Comment by sktomer** [comment]
Hi,

`2023.6.20241031.0` release is out for some time now and shows no vulnerabilities.
We try to get new releases out in time, sometimes there can be unexpected delays.
