### ISSUE TITLE
 awscli pkg in AL2023 image and image updates notification SNS

### ISSUE THREAD

**Issue by SHAISRIN000** [amazonlinux/container-images#119]
### Product

Amazon Linux 2023

### Package

awscli-2	

### Why do you need this package?

AL2023 minimal AMI has awscli-2 ,can this package made it available in container image as well. We have to maintain tooling to install awscli on top of the base image ,trying to avoid this.

There is a [subscription](https://docs.aws.amazon.com/linux/al2023/ug/receive-update-notification.html) available for  AL 2023 AMI updates ,can we have similar notification for images as well. Currently we had a lambda that checks imagePushedAt from the [aws cli](https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-images.html).

**Comment by sktomer** [comment]
So to breakdown your requests:
* request to add `awscli-2` in container image
* notification mechanism for AMIs so you don't have to poll EC2 describe images.

I can review the 1st one with my team.
For the second one, can you use SSM parameters or SSM parameter update triggers ?

See:
https://docs.aws.amazon.com/linux/al2023/ug/ec2.html#launch-via-aws-cli
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-cwe.html

**Comment by sktomer** [comment]
Our goal for container images is to keep the pre-installed set of packages to the minimum core components. AWS CLI does not fall in that category and hence cannot be included.

If you just need awscli container ... maybe you can try: https://hub.docker.com/r/amazon/aws-cli
