### ISSUE TITLE
Update docker to 18.09

### ISSUE THREAD

**Issue by LennyPenny** [amazonlinux/container-images#24]
Are there any news when docker 18.09 will be available on amazon linux?

**Comment by jhaynes** [comment]
Hi @LennyPenny While we don't have a firm date for Docker 18.09's availability on Amazon Linux, we absolutely take customer feedback into consideration when releasing new versions. Are there specific features or bug fixes you're looking for?

**Comment by LennyPenny** [comment]
Hey @jhaynes, thanks for the reply! 
Docker 18.09 finally includes a stable version of docker buildkit (https://blog.docker.com/2018/11/introducing-docker-engine-18-09/ under BuildKit Improvements) which includes a bugfix we require for our ci proccess!

**Comment by xyvark** [comment]
We faced the following issue https://github.com/moby/moby/issues/38766 a couple of weeks ago and it was fixed in version 18.09. Thanks!

**Comment by megamorf** [comment]
I also want to use buildkit. Is there an ETA for 18.09?

**Comment by rrroo** [comment]
@jhaynes We currently see quite a few cases of https://github.com/opencontainers/runc/issues/1884, which are fixed in 18.09.

**Comment by kainoaseto** [comment]
Hey @jhaynes, We are also looking to leverage the Buildkit functionalities of 18.09 for our CI processes and was wondering if there has been any progress on getting that updated in Amazon Linux? The bugs above are also a little concerning since we use docker heavily in our production systems and it would be unfortunate to come across those with no recourse.

**Comment by jhaynes** [comment]
Hi all, thanks for the feedback and patience. Buildkit support is something we're excited about too as well as getting fixes for the bugs linked. While I can't give a firm date, I can definitely say we're working to get the latest stable Docker 18.09 into you hands soon!

**Comment by daveisfera** [comment]
@jhaynes Any update on this?

**Comment by jhaynes** [comment]
Hi all, Docker 18.09.9 is available now for AL1 and AL2.

**Comment by daveisfera** [comment]
Saaaaweeeet!
