### ISSUE TITLE
adduser

### ISSUE THREAD

**Issue by adaniline-traderev** [amazonlinux/container-images#28]
adduser is not part of the image...
If I don't want to run my app as root, what is the way to add an app user to my image?

**Comment by iliana** [comment]
Would something like this work?

```
FROM amazonlinux:2
RUN yum install -y shadow-utils && yum clean all && useradd user
USER user
```

**Comment by yosifkit** [comment]
For docker, the user id doesn't have to exist to use it :wink::

```dockerfile
FROM amazonlinux:2
USER 1000
```

**Comment by adaniline-traderev** [comment]
Thank you, good to know!
I did not realize it is possible - I always was adding users to the image..

**Comment by Veetaha** [comment]
For those desperate souls that can't find `useradd` in this image. Here is my blessing. It is there, you already have it in possession. No need to thank, I already spent time figuring this out, just use `useradd` though an absolute path, because it is not in `PATH` by default in Amazon Linux 2.

```
/usr/sbin/useradd $YOUR_USER
```
