### ISSUE TITLE
Dockerfile to replicate EC2 image

### ISSUE THREAD

**Issue by tvogel8570** [amazonlinux/container-images#33]
My request is for there to be a supported / maintained version of a Dockerfile (not an image) to go from the bare amazonlinux:2 docker image to the configuration when using an EC2 instance from the AWS Linux 2 AMI.

I have read the other issues, as well as posts on AWS support, about keeping the image small.  This makes sense in general but doesn't fit my use case.

I need to be confident that software developed on a docker image will perform the same when deployed to EC2.  However I'm NOT a linux admin and have no idea of all the steps needed to get even close to the EC2 image.  

Thanks for considering my request,
Timothy

**Comment by iliana** [comment]
Hi,

For AL2 you can use `yum groupinstall` to install the list of packages we install to AMIs.

You can install the package set from the AMI by performing `yum groupinstall -y ami`, and for the minimal AMI with `yum groupinstall -y ami-minimal`.

Full list:

```plain
zcat /var/cache/yum/x86_64/2/amzn2-core/comps.xml.gz | grep '<id>'
    <id>core</id>
    <id>container</id>
    <id>base-minimal</id>
    <id>base</id>
    <id>ami-minimal</id>
    <id>onprem-minimal</id>
    <id>onprem</id>
    <id>ami</id>
    <id>aws-tools</id>
    <id>development</id>
    <id>buildsys</id>
```
