### ISSUE TITLE
Please, include UTF-8 encoding into the Amazon Linux base images

### ISSUE THREAD

**Issue by Sam-Kruglov** [amazonlinux/container-images#36]
Hi, we are using amazonlinux:2 base image in our containers and just recently discovered that when services talk via a network, some symbols get replaced with question marks.
We fixed the issue by adding this line to our main Dockerfile:
```dockerfile
ENV LC_ALL en_US.UTF-8
```
Originally posted [here](https://forums.aws.amazon.com/message.jspa?messageID=922034#922034)
Might be related to #26

**Comment by cmccoypdx** [comment]
We have discussed this internally. Setting anything but the most minimal of environment variables does not seem to be a common practice for Linux container base layers, as demonstrated with a few popular distributions:

```
% docker run -it --rm --entrypoint /usr/bin/env ubuntu:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=b59008c2d29e
TERM=xterm
HOME=/root

% docker run -it --rm --entrypoint /usr/bin/env centos:latest
Unable to find image 'centos:latest' locally
latest: Pulling from library/centos
a1d0c7532777: Pull complete
Digest: sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177
Status: Downloaded newer image for centos:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ec0f5ba2d67d
TERM=xterm
HOME=/root

% docker run -it --rm --entrypoint /usr/bin/env fedora:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a07416d80eaa
TERM=xterm
DISTTAG=f38container
FGC=f38
FBR=f38
HOME=/root

% docker run -it --rm --entrypoint /usr/bin/env debian:latest
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
b0248cf3e63c: Pull complete
Digest: sha256:0a78ed641b76252739e28ebbbe8cdbd80dc367fba4502565ca839e5803cfd86e
Status: Downloaded newer image for debian:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a94767911100
TERM=xterm
HOME=/root
```

Given that enabling UTF-8 in a derived container image or via a startup script should be trivial, we are going to err on the side of not causing confusion by deviating from common behavior for now. We may revisit this in the future if enough interest is shown.
