### ISSUE TITLE
Update to 20.10

### ISSUE THREAD

**Issue by daveisfera** [amazonlinux/container-images#43]
20.10 has been out for several months now and has improved support for buildkit (which is being pushed as the preferred method for building docker images going forward), so can it be made available?

**Comment by mrthornazon** [comment]
`docker-20.10.17-1.amzn2.0.2.x86_64` is available in the AL2 Extras Docker topic.
You can see the CVEs addressed on the Amazon Linux Security Center: https://alas.aws.amazon.com/AL2/ALASDOCKER-2021-001.html
