### ISSUE TITLE
Amazon Linux 2022 container images missing ??

### ISSUE THREAD

**Issue by dimetron** [amazonlinux/container-images#53]
Hi, 

Amazon Linux 2022 announced - is there a corresponding container image ? 
https://forums.aws.amazon.com/ann.jspa?annID=9039

**Comment by mysteriouspants** [comment]
Hi,

Sorry for the delay in answering. This is definitely on our roadmap - we're working on it.

Thanks!

**Comment by leandrorebelo** [comment]
It was released: https://github.com/amazonlinux/amazon-linux-2022/issues/2

**Comment by sktomer** [comment]
Hello,

AL 2022 Tech Preview Container Images are available in private/public ECR and DockerHub:
* https://gallery.ecr.aws/amazonlinux/amazonlinux
* https://hub.docker.com/_/amazonlinux
