### ISSUE TITLE
ImageMagick latest packages missing in amazonlinux image

### ISSUE THREAD

**Issue by yrsurya** [amazonlinux/container-images#56]
bash-4.2# yum list installed | grep Image
ImageMagick.x86_64                          6.9.10.68-5.amzn2.0.1    @amzn2-core
bash-4.2# convert --version
Version: ImageMagick 6.9.10-68 Q16 x86_64 2021-02-02 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff wmf x xml zlib

Any plans on getting latest version available ?
https://imagemagick.org/script/download.php
ImageMagick-7.1.0-17 is latest version

**Comment by cmccoypdx** [comment]
Apologies for the long delay in responding to this issue. ImageMagick 7.x is not a direct upgrade from 6.x, but rather a complete rewrite, and scripts written for 6.x are incompatible with 7.x: https://imagemagick.org/script/porting.php. Therefore, we cannot replace ImageMagick 6.x with 7.x without breaking customers. 

We will not be adding ImageMagick 7.x to Amazon Linux 2. We had a discussion this week to consider adding 7.x as a second version of ImageMagick to AL2023 (the latest version of Amazon Linux available via the amazonlinux:latest tag), but as we already ship 6.x in AL2023 as well, we have decided that maintaining both is not feasible at this time, and will not be adding it to AL2023 at this time either.
