### ISSUE TITLE
File-libs library using older version of file command and magic numbers

### ISSUE THREAD

**Issue by anshulsinghchauhan** [amazonlinux/container-images#59]
Hi All,
I can see the file libs and file command available are outdated they are pointing to version 5.11.
Is there a way to upgrade it to the latest version.
Please provide a package with the latest file command and file-libs holding latest magic numbers.

**Comment by stewartsmith** [comment]
AL2023 has updated many updates, including the `file` utility moving from `5.11-36.amzn2.0.1` to `5.39-7.amzn2023.0.2`
