### ISSUE TITLE
Fix for security issue ALAS2-2022-1764

### ISSUE THREAD

**Issue by ghsatpute-freshworks** [amazonlinux/container-images#66]
We are using Docker image `amazonlinux:2`

Amazon Linux has security issue [ALAS2-2022-1764](https://alas.aws.amazon.com/AL2/ALAS-2022-1764.html)

The fix given is to run `yum update expat` but I see that this image is not yet updated. Any update on when are we going to release a new Docker image with a fix for this issue?

**Comment by mysteriouspants** [comment]
Hello,

While I don't have an ETA for when new container images will hit ECR/DockerHub, we are actively working on releasing new containers and AMIs which will include this update. I will leave this issue open until that release is completed.

Thanks,
Chris

**Comment by ghsatpute-freshworks** [comment]
Thanks for the update, Chris! 🙏

**Comment by mysteriouspants** [comment]
Amazon Linux 2 has released new container images to ECR and ECR Public which include the patched version of expat on the image, as well as new AMIs. We are currently working on getting the same containers available in DockerHub. I will close this ticket when DockerHub is updated. Thanks for your patience!

**Comment by mysteriouspants** [comment]
It looks like this was patched in [2.0.20220316.0](https://hub.docker.com/layers/amazonlinux/library/amazonlinux/2.0.20220316.0-with-sources/images/sha256-482a94c2fbb091d98d5f458dad127758f4774d6c850386b8e9f637099fa92463?context=explore) which is available on Docker Hub now. Closing ticket.
