### ISSUE TITLE
Docker Image missing

### ISSUE THREAD

**Issue by dumbworker** [amazonlinux/container-images#77]
https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20220606.html
Says the June image is available but the image is not available on Dockerhub.  https://hub.docker.com/_/amazonlinux?tab=tags
When will this be made available?
TIA

**Comment by mysteriouspants** [comment]
The 20220606.1 release is available on Docker Hub now. https://hub.docker.com/layers/amazonlinux/library/amazonlinux/2.0.20220606.1/images/sha256-c9ce7208912b7897c9a4cb273f20bbfd54fd745d1dd64f5e625fff6778469e69?context=explore

Thanks for your patience!

**Comment by dumbworker** [comment]
@mysteriouspants 
The same issue with https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20220802.html, the new image is not published. Could you please update this?
