### ISSUE TITLE
amazonlinux:2022 not support amazon-linux-extras command

### ISSUE THREAD

**Issue by citycan1991** [amazonlinux/container-images#80]
Hi, I'm try to use amazonlinux:2022 as our base image, and I can see [amazon-linux-extras] this command everywhere.
but actually I got command not found after input amazon-linux-extras install xxx.

By the way, the default yum repo provide few packages. when I tried to add epel repo(by command:
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm), I got this error:
Error: 
 Problem: conflicting requests
  - nothing provides redhat-release >= 7 needed by epel-release-7-14.noarch
(try to add '--skip-broken' to skip uninstallable packages)

how can I fix these problems to install extras tools or packages.
Look forward to your reply，ths!

**Comment by Kemotaha** [comment]
Thanks for your request.  Amazon Linux 2022 does not include `amazon-linux-extras` or the functionality to enable extra repositories at this time.

In addition, AL2022 is not compatible with EPEL or a similar repository at this time.  EPEL are community built packages that are available for Enterprise Linux versions, which AL2 was closely related to EL7 versions. For more information please see the documentation about AL2022 and EPEL: https://docs.aws.amazon.com/linux/al2022/ug/compare-al2-to-AL2022.html#epel

**Comment by sktomer** [comment]
No possible action items.
