### ISSUE TITLE
amzn container images are FIPS complaint ?

### ISSUE THREAD

**Issue by aramsamy** [amazonlinux/container-images#89]
Are the AMZN container images compliant with FIPS? If not, when can we expect them to become a part of the image?

**Comment by aramsamy** [comment]
Can you please check this issue ?

**Comment by mysteriouspants** [comment]
I'm forwarding this to our Security group who can answer this question.

**Comment by stewartsmith** [comment]
AL2 images do have FIPS certs for components, we are in the process of getting certs for AL2023.
