### ISSUE TITLE
Issues with node14/node16 install on amazonlinux:latest

### ISSUE THREAD

**Issue by flyingalphaunicorn** [amazonlinux/container-images#92]
Running into the following issue with node14/node16 install with amazonlinux:latest

 RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash
 ---> Running in 55eb9a772563

## Inspecting system...

+ rpm -q --whatprovides redhat-release || rpm -q --whatprovides centos-release || rpm -q --whatprovides cloudlinux-release || rpm -q --whatprovides sl-release || rpm -q --whatprovides fedora-release
+ uname -m

## You don't appear to be running a supported version of Enterprise Linux. Please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your architecture to be considered for support. Include your 'distribution package' name: no package provides redhat-release
no package provides centos-release
no package provides cloudlinux-release
no package provides sl-release
no package provides fedora-release. 

The command '/bin/sh -c curl -sL https://rpm.nodesource.com/setup_14.x | bash' returned a non-zero code: 1

Also reported here
 https://github.com/nodesource/distributions/issues/1524

Will this be fixed ?

**Comment by sktomer** [comment]
Does this help?
https://github.com/amazonlinux/container-images/issues/90#issuecomment-1481546688

**Comment by flyingalphaunicorn** [comment]
It does for now ! appreciate the help @sktomer

**Comment by pranjalja1n** [comment]
@flyingalphaunicorn Were you able to install npm as well? I followed your instructions to install node but npm is still missing after

`RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash`
