### ISSUE TITLE
No match for argument: java-1.8.0-openjdk-devel

### ISSUE THREAD

**Issue by mmacagno** [amazonlinux/container-images#94]
```
FROM amazonlinux:latest 
...
##Installing java
RUN yum install java-1.8.0-openjdk-devel -y && RUN amazon-linux-extras install java-openjdk11

```
causes the error:

```
=> ERROR [17/47] RUN yum install java-1.8.0-openjdk-devel -y && amazon-linux-extras install java-openjdk11           0.6s

------                                                                                                                     

> [17/47] RUN yum install java-1.8.0-openjdk-devel -y && amazon-linux-extras install java-openjdk11:

#20 0.509 Last metadata expiration check: 0:12:45 ago on Fri Mar 31 20:04:22 2023.

#20 0.528 No match for argument: java-1.8.0-openjdk-devel

#20 0.540 Error: Unable to find a match: java-1.8.0-openjdk-devel
```

Thanks

**Comment by mmacagno** [comment]
It seems same problem as #90. I reverted to public.ecr.aws/amazonlinux/amazonlinux:2 and it works.

**Comment by sktomer** [comment]
Hello,

Please note that the `latest` tag will always point to the latest Amazon Linux OS. There are differences in the Amazon Linux 2 and Amazon Linux 2023 repo configuration as well as package lists. If you application requires a specific package version or uses `amazon-linux-extras`, then most likely it will require changes to work with Amazon Linux 2023.

The supported tags list and related documentation can be found here: https://gallery.ecr.aws/amazonlinux/amazonlinux
AL2 vs AL202: https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html
