### ISSUE TITLE
[Question]: Using EKS/gitlab-runners via Helm I can't use docker in docker anymore with AmazonLinux:2023

### ISSUE THREAD

**Issue by cmcniel** [amazonlinux/container-images#95]
### Product

Amazon Linux 2023

### What is your question?

I have a pipeline using EKS/gitlab-runners via Helm that use an AmazonLinux:2 build image.   This has worked great for years.   Recently tried to update the container to use AmazonLinux:2023 and now seccomp seems to be getting involved and I can't understand how to get around it.

I can still build my legacy AmazonLinux:2 containers but, the updated Dockerfile using a FROM: amazonlinux:2023 fails almost immediately when I try to use dnf to install packages.

I recieved the following error during the pipeline run.

 ---> Running in cf9d48f02b84
Amazon Linux 2023 repository                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'amazonlinux':
  _### - **Curl error (6): Couldn't resolve host name for**_ https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list [getaddrinfo() thread failed to start]
Ignoring repositories: amazonlinux

I was able to reproduce this locally as well trying docker in docker.   However passing in the flag to docker run 

`--security-opt seccomp=unconfined`

I was able to work around this.   Unfortunately you cannot pass this flag to docker build so I'm unable to move this forward and need to figure out how to disable this feature in the Amazonlinux:2023 image.

https://docs.aws.amazon.com/linux/al2023/ug/install-docker.html

**Comment by vedimuthan** [comment]
Same issue,

Error: Failed to download metadata for repo 'amazonlinux': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://cdn.amazonlinux.com/al2023/core/mirrors/2023.0.20230322/x86_64/mirror.list [getaddrinfo() thread failed to start]

**Comment by mysteriouspants** [comment]
This looks like the same issue as https://github.com/amazonlinux/amazon-linux-2023/issues/80#issuecomment-1017798237.

You will have to get an update to your Docker installation with an updated seccomp policy to correct this. It's unfortunately not something that can be fixed on the AL2023 container itself.

If you update to the latest version of Docker and the problem persists please reopen this and we'll take another look. Thanks!
