### ISSUE TITLE
[Question]: Missing AL2 images on Dockerhub

### ISSUE THREAD

**Issue by dumbworker** [amazonlinux/container-images#96]
### Product

Amazon Linux 2

### What is your question?

https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20230424.html says the April image is available but the image is not available on Dockerhub. https://hub.docker.com/_/amazonlinux?tab=tags
When will this be made available?
TIA

**Comment by sktomer** [comment]
Thank you for bringing this to our attention @dumbworker .

The DockerHub updates can be delayed by upto 1 week from the date of an official AMI release version. However in this particular case, it was a miss on our side. We are pushing the updates out now and will ensure we track this work better going forward.

**Comment by mrthornazon** [comment]
Here is the pull request which will update images: https://github.com/docker-library/official-images/pull/14587

**Comment by dumbworker** [comment]
Seeing the latest images , thank you @sktomer and @mrthornazon.
