### ISSUE TITLE
[Question]: Missing AL2 images on Dockerhub

### ISSUE THREAD

**Issue by dumbworker** [amazonlinux/container-images#97]
### Product

Amazon Linux 2

### What is your question?

https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20230607.html says the June image is available but the image is not available on Dockerhub. https://hub.docker.com/_/amazonlinux?tab=tags, latest i see is this docker pull amazonlinux:2023.0.20230517.1
When will this be made available?
TIA

**Comment by cmccoypdx** [comment]
From our Readme:

> Amazon Linux is able to update our first-party sources (ECR) same-day as the associated AMI release. To reduce the operational load on the Docker Official Images program, we batch our OS releases and submit them weekly.

The 2023.06.07 image is available in ECR: https://gallery.ecr.aws/amazonlinux/amazonlinux. We will be submitting a PR to Docker Hub today to pick up last week's releases.

**Comment by cmccoypdx** [comment]
PR submitted to Docker Official Images: https://github.com/docker-library/official-images/pull/14826
